apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - restrict-rbac-rules.yaml
  - restrict-rbac-rules-binding.yaml
  - restrict-rbac-binding.yaml
  - restrict-rbac-binding-binding.yaml
  - restrict-tunnel-hostname.yaml
  - restrict-tunnel-hostname-binding.yaml
  - protect-cloudflare-gateway.yaml
  - protect-cloudflare-gateway-binding.yaml
