apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: restrict-rbac-rules
  labels:
    app.kubernetes.io/part-of: policies
spec:
  policyName: restrict-rbac-rules
  validationActions: [Audit, Warn]
  # Phase D2 で [Deny] に切り替える
