apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: netstress-k8s
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/ROBO358/netstress-k8s
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netstress
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  path: ./manifests
  prune: true
  serviceAccountName: flux-netstress
  dependsOn:
    - name: cilium-config
    - name: cert-manager-config
    - name: cloudflare-gateway-config
  sourceRef:
    kind: GitRepository
    name: netstress-k8s
  wait: true
  timeout: 10m
