apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-speedtest
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-speedtest-role
  labels:
    app.kubernetes.io/part-of: apps
rules:
  # Namespace is created by platform (apps/<app>/namespace.yaml); SA only needs read
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [services]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [apps]
    resources: [deployments, replicasets]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [cert-manager.io]
    resources: [certificates]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [gateway.networking.k8s.io]
    resources: [gateways, httproutes]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [cilium.io]
    resources: [ciliumnetworkpolicies]
    verbs: [get, list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-speedtest-scoped
  labels:
    app.kubernetes.io/part-of: apps
subjects:
  - kind: ServiceAccount
    name: flux-speedtest
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-speedtest-role
