apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 12h
  url: https://github.com/kubernetes-sigs/external-dns
  ref:
    tag: external-dns-helm-chart-1.21.1
  ignore: |
    /*
    !/charts/
