apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 10m
  serviceAccountName: helm-external-dns
  releaseName: external-dns
  targetNamespace: external-dns
  chart:
    spec:
      chart: ./charts/external-dns
      sourceRef:
        kind: GitRepository
        name: external-dns
        namespace: external-dns
      interval: 12h
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    serviceAccount:
      create: false
      name: helm-external-dns
    rbac:
      create: false
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: api-token
    sources:
      - gateway-httproute
    extraArgs:
      - --gateway-name=*
    policy: sync
    registry: txt
    txtOwnerId: yh-cluster
    txtPrefix: _extdns-
    domainFilters:
      - yh.k8s.tsuru.run
    logLevel: debug
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: monitoring
