apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  serviceAccountName: helm-cert-manager
  releaseName: cert-manager
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      # Keep in sync with Taskfile.yml CM_VERSION
      version: "v1.16.2"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      interval: 12h
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    crds:
      enabled: true
      keep: true
    replicaCount: 2
    webhook:
      replicaCount: 2
    cainjector:
      replicaCount: 2
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
