apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-github-client
  namespace: dex
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dex-github-client
  data:
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: dex-github-oauth/client-id
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: dex-github-oauth/client-secret
