apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: yh-cluster
  namespace: cloudflare-gateway
spec:
  gatewayClassName: cloudflare
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - speedtest
                  - mirotalk
                  - sample-app
                  - dex
                  - monitoring
