apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: healthchecks-scrape-config
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: healthchecks-scrape-config
    template:
      data:
        scrape-config.yaml: |
          - job_name: healthchecks
            scheme: https
            metrics_path: /projects/{{ .project_uuid }}/metrics/{{ .api_key }}
            scrape_interval: 60s
            static_configs:
              - targets: ['healthchecks.io']
  data:
    - secretKey: project_uuid
      remoteRef:
        key: monitoring-healthchecks/project-uuid
    - secretKey: api_key
      remoteRef:
        key: monitoring-healthchecks/api-key
