apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-grafana-cloud
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: monitoring-grafana-cloud
  dataFrom:
    - extract:
        key: monitoring-grafana-cloud
