apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sa.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - externalsecret-grafana-admin.yaml
  - externalsecret-grafana-cloud.yaml
  - externalsecret-healthchecks.yaml
  - externalsecret-discord.yaml
