apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-monitoring
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: flux-rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-monitoring-scoped
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: helm-monitoring
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-monitoring-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-monitoring-ns-admin
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: helm-monitoring
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
