apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-gateway-api-crds
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-cilium
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-cilium-config
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-external-secrets
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-external-secrets-config
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-longhorn
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-cert-manager
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-cert-manager-config
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-dex
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-dex-config
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-rbac-humans
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-monitoring
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-monitoring-config
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-cloudflared
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux-rbac
