apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-cilium-applier
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-cilium
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-external-secrets-applier
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-external-secrets
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-longhorn-applier
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-longhorn
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-cert-manager-applier
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-cert-manager
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-dex-applier
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-dex
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
