apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-rbac-humans-scoped
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-rbac-humans
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-rbac-humans-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-gateway-api-crds-scoped
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-gateway-api-crds
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-gateway-api-crds-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-cilium-config-scoped
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-cilium-config
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-cilium-config-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-external-secrets-config-scoped
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-external-secrets-config
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-external-secrets-config-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-cert-manager-config-scoped
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-cert-manager-config
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-cert-manager-config-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-dex-config-scoped
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-dex-config
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-dex-config-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-cilium-scoped
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-cilium
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-cilium-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-external-secrets-scoped
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-external-secrets
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-external-secrets-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-longhorn-scoped
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-longhorn
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-longhorn-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-cert-manager-scoped
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-cert-manager
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-cert-manager-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-dex-scoped
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-dex
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-dex-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-monitoring-scoped
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-monitoring
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-monitoring-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-monitoring-config-scoped
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-monitoring-config
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-monitoring-config-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-cloudflared-scoped
  labels:
    app.kubernetes.io/part-of: flux-rbac
subjects:
  - kind: ServiceAccount
    name: flux-cloudflared
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-cloudflared-role
